name: Upload to S3

on: [pull_request]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
      - name: Configure AWS Credentials
      - uses: aws-actions/configure-aws-credentials@v4
      - name: Upload to S3 using AWS CLI
      - run: aws s3 sync ./ s3://${{ secrets.S3_BUCKET_NAME }} --delete
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'dirname'
